
language: python
matrix:
  include:
  - name: "3.10.2 Unittest"
    python: "3.9"
    env: TEST_SUITE=UNITTEST

install:
  - pip install -r requirements-dev.txt

branches:
  only:
  - main

script: 
  - make tests

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  api_key:
    secure: $TOKEN_PROJECT
  app: test-word
  on:
    all_branches: true
