
language: python
matrix:
  include:
  - name: "3.10.2 Unittest"
    python: "3.9"
    env: TEST_SUITE=UNITTEST

install:
  - pip install -r requirements-dev.txt

branches:
  only:
  - main

script: 
  - make tests

deploy:
  provider: heroku
  api_key:
    secure: "d9fe9101-dbca-4180-a2c0-3e20e7efe2b9"
  app: test-word
  on:
    all_branches: true
