
language: python
matrix:
  include:
  - name: "3.10.2 Unittest"
    python: "3.9"
    env: TEST_SUITE=UNITTEST

install:
  - pip install -r requirements-dev.txt

branches:
  only:
  - main

script: 
  - make tests-with-coverage

after_success:
  - coveralls
